#!/bin/sh

### BEGIN INIT INFO
# Provides:          jetsonproxydaemon
# Required-Start:    $local_fs $network $syslog
# Required-Stop:     $local_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Jetsonproxy
# Description:       Jetsonproxy start-stop-daemon - Debian
### END INIT INFO

NAME="jetsonproxy"
PATH="/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin"
APPDIR="/home/nvidia/Cyclone_scripts"
APPBIN="/home/nvidia/Cyclone_scripts/mavproxy-jetson.sh"
APPARGS=""
USER="nvidia"
GROUP="nvidia"

# Include functions 
set -e
. /lib/lsb/init-functions

start() {
  printf "Init: Starting '$NAME'...\n "
  #start-stop-daemon --start --chuid "$USER:$GROUP" --background --make-pidfile --pidfile /var/run/$NAME.pid --chdir "$APPDIR" --exec "$APPBIN" -- $APPARGS || true
  start-stop-daemon --start --chuid "$USER:$GROUP" --make-pidfile --pidfile /var/run/$NAME.pid --chdir "$APPDIR" --exec /home/nvidia/Cyclone_scripts/mavproxy-jetson.sh
  printf "Init: Done\n"
}

#We need this function to ensure the whole process tree will be killed
killtree() {
    local _pid=$1
    local _sig=${2-TERM}
    for _child in $(ps -o pid --no-headers --ppid ${_pid}); do
        killtree ${_child} ${_sig}
    done
    kill -${_sig} ${_pid}
}

stop() {
  printf "Init: Stopping '$NAME'... \n"
  #su odroid -c "screen -S MavProxy -X quit"
  su nvidia -c "/home/nvidia/Cyclone_scripts/mavproxy-stop-jetson.sh"
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || \
  while test -d /proc/$(cat /var/run/$NAME.pid); do
    killtree $(cat /var/run/$NAME.pid) 15
    sleep 0.5
  done 
  [ -z `cat /var/run/$NAME.pid 2>/dev/null` ] || rm /var/run/$NAME.pid
  printf "Init: Done\n"
}

status() {
  status_of_proc -p /var/run/$NAME.pid "" $NAME && exit 0 || exit $?
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $NAME {start|stop|restart|status}" >&2
    exit 1
    ;;
esac

exit 0
